There is two way acessing data from internet/web:
    1.http[usually used]
    2.API[Application Programming Interface]

# 1. Http

1.usually for reciving data from web/internet we use http[hyper text transport protocal] there we got the Data in HTML and CSS form[web page]

# 2. API

API is the pipline between two software.
In simplest form API is the simplest function which we put on the server which has some url, after hitting on that url and passing the correct parametes,Its give us some response/result in JSON[[javascript object notation] format.

Create the account on API

In [1]:
# now for practice purpose i will created the account on [TMDB API]

By the way short note on API

Now a current Scenario/econamy prespective, API are very important.
Ex.,
when we can book the train tickit by IRCT, makemytrip,exigo,goibo.....
ok,once the particular tickit is booked from the IRCT, can that tickit also show booked on makemytrip,goibo... the answer is yes and you cant do transaction on it.
Now think about it ,the DATABASE is of IRTC but every company know which seat is booked or not Because they are communicating with IRCT DATABASE by their API.

In [9]:
import requests
import pandas as pd
import numpy as np

In [3]:
response=requests.get('https://api.themoviedb.org/3/movie/popular?api_key=290c56582df36f9e41f90ba8edf56fad&language=en-US&page=1').json()

In [4]:
popularity=[]
vote_count=[]
original_language=[]
vote_average=[]
overview=[]
release_date=[]

for i in response['results']:
    
    popularity.append(i['popularity'])
    vote_count.append(i['vote_count'])
    original_language.append(i['original_language'])
    vote_average.append(i['vote_average'])
    overview.append(i['overview'])
    release_date.append(i['release_date'])
    
d={'popularity':popularity,'vote_count':vote_count,'original_language':original_language,'vote_average':vote_average,'overview':overview,'release_date':release_date}    
df=pd.DataFrame(d)
df

,popularity,vote_count,original_language,vote_average,overview,release_date
0,7631.138,574,en,7.4,"For best friends Becky and Hunter, life is all...",2022-08-11
1,6529.681,298,en,7.1,A recently widowed man and his two teenage dau...,2022-08-11
2,5010.923,431,en,6.8,A wooden puppet embarks on a thrilling adventu...,2022-09-07
3,4548.226,331,te,7.9,A fictional history of two legendary revolutio...,2022-03-24
4,3612.381,1581,ja,8.0,"The Red Ribbon Army, an evil organization that...",2022-06-11
5,3474.459,3276,en,6.8,After his retirement is interrupted by Gorr th...,2022-07-06
6,3348.480,962,en,7.0,Thirteen year old Sam Cleary suspects that hi...,2022-08-25
7,2746.083,49,en,7.3,New recruit Justin Rosa must monitor arms-smug...,2022-09-02
8,2586.824,88,ja,7.0,In this sequel to the 2017 live-action netflix...,2022-05-20
9,2353.634,3816,en,8.0,"When danger threatens her camp, the fierce and...",2022-08-02
10,1983.136,67,ko,6.9,"Chasing speed, dreams and money, a team of dri...",2022-08-26
11,1902.250,522,en,7.6,When Superman and the rest of the Justice Leag...,2022-07-27
12,1749.604,3322,en,7.1,"Four years after Isla Nublar was destroyed, di...",2022-06-01
13,1717.452,3695,en,8.4,After more than thirty years of service as one...,2022-05-24
14,1571.505,274,ja,7.7,Yuta Okkotsu is a nervous high school student ...,2021-12-24
15,1554.270,65,it,5.0,"Carezza and Sorriso, brothers very different f...",2022-03-23
16,1551.214,1917,en,7.6,A fanboy of a supervillain supergroup known as...,2022-06-29
17,1312.414,55,en,6.5,Billionaire sportsman Buddy King unwinds by hu...,2022-04-01
18,1237.088,57,en,6.9,When a crooked federal agent is involved in a ...,2022-08-15
19,1230.810,1413,en,7.0,Residents in a lonely gulch of inland Californ...,2022-07-20

In [15]:
final=pd.DataFrame()
popularity=[]
vote_count=[]
original_language=[]
vote_average=[]
overview=[]
release_date=[]

for j in range(1,500):
    response=requests.get('https://api.themoviedb.org/3/movie/popular?api_key=290c56582df36f9e41f90ba8edf56fad&language=en-US&page={}'.format(j)).json()
    popularity=[]
    vote_count=[]
    original_language=[]
    vote_average=[]
    overview=[]
    release_date=[]
    for i in response['results']:
        try:

            popularity.append(i['popularity'])
        except:
            popularity.append(np.nan)
        try:
            
            vote_count.append(i['vote_count'])
        except:
             vote_count.append(np.nan)
        try:
            
            original_language.append(i['original_language'])
        except:
            
            
            original_language.append(np.nan)
        try:
            
            vote_average.append(i['vote_average'])
        except:
            vote_average.append(np.nan)
        try:
            
            overview.append(i['overview'])
        except:
            overview.append(np.nan)
        try:
            
            release_date.append(i['release_date'])
        except:
            release_date.append(np.nan)

    d={'popularity':popularity,'vote_count':vote_count,'original_language':original_language,'vote_average':vote_average,'overview':overview,'release_date':release_date}    
    df=pd.DataFrame(d)
    
    final=final.append(df,ignore_index=True)

final

C:\Users\Vishal Ghuge\AppData\Local\Temp\ipykernel_31012\810097167.py:54: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final=final.append(df,ignore_index=True)

,popularity,vote_count,original_language,vote_average,overview,release_date
0,7631.138,574,en,7.4,"For best friends Becky and Hunter, life is all...",2022-08-11
1,6529.681,298,en,7.1,A recently widowed man and his two teenage dau...,2022-08-11
2,5010.923,431,en,6.8,A wooden puppet embarks on a thrilling adventu...,2022-09-07
3,4548.226,331,te,7.9,A fictional history of two legendary revolutio...,2022-03-24
4,3612.381,1581,ja,8.0,"The Red Ribbon Army, an evil organization that...",2022-06-11
...,...,...,...,...,...,...
9975,11.166,357,es,6.7,"Madrid, summer 2011. Economic crisis. 15-M mov...",2016-10-28
9976,11.162,3,en,3.3,A coming of age film about a group of high sch...,2022-09-09
9977,11.162,482,en,6.6,Loosely based on the Charles Dickens' classic ...,1998-01-30
9978,11.161,87,ru,7.2,A very typical post-Soviet era storyline. A bu...,1999-04-19
9979,11.161,375,en,5.9,Underwater deep-sea miners encounter a Soviet ...,1989-03-17